export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const CHANGE_CURRENT_USER = "CHANGE_CURRENT_USER";
export const CHANGE_CURRENT_POST = "CHANGE_CURRENT_POST";
